// #Sireum

package org.sireum.hamr.arsit.templates

import org.sireum._

object StringTemplate {

  def doNotEditComment(): String = {
    return "// Do not edit this file as it will be overwritten if HAMR codegen is rerun"
  }

  def safeToEditComment(): String = {
    return "// This file will not be overwritten so is safe to edit"
  }
}
