name: Windows

on:
  push:
  workflow_dispatch:

jobs:

  ci:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Cygwin
        shell: cmd
        run: |
          choco config get cacheLocation
          choco install --no-progress cygwin
          C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P gcc-core,gcc-g++,make,cmake
      - name: Retrieve versions.properties
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/sireum/kekinian/master/versions.properties" -OutFile "versions.properties"
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v2
        with:
          path: bin\win\java
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-java
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v2
        with:
          path: bin\scala
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v2
        with:
          path: cache\coursier
          key: ${{ runner.os }}-${{ hashFiles('versions.properties') }}-coursier
      - name: Check LongPathsEnabled
        run: |
          (Get-ItemProperty "HKLM:System\CurrentControlSet\Control\FileSystem").LongPathsEnabled
      - name: Test
        shell: cmd
        run: |
          xcopy %GITHUB_WORKSPACE%\cache\coursier %HOMEDRIVE%%HOMEPATH%\cache\coursier\ /E/H
          set COURSIER_CACHE=%HOMEDRIVE%%HOMEPATH%\cache\coursier
          set PATH=C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin;%PATH%
          set CC=gcc.exe
          set CXX=c++.exe
          cd /d %GITHUB_WORKSPACE%
          
          echo Need to add back 'compile' mode once github actions issue is resolved
          set HamrTestModes=ProyekCompile,ProyekTest,ProyekRun,LinuxCompile
          echo HamrTestModes=%HamrTestModes%

          bin\build.cmd test